# Generated by Django 6.0 on 2026-02-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='cerrado_por',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incidente',
            name='creado_por',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
